const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
  console.log('Sembrando datos reales de Cartones America...')

  await prisma.tarea.deleteMany()
  await prisma.actividad.deleteMany()
  await prisma.oportunidad.deleteMany()
  await prisma.cliente.deleteMany()

  // ─── CLIENTES ACTIVOS (fuente: CLIENTES 2025 VACACIONES ABRIL - Hoja2) ───
  const clientes = await Promise.all([

    // ── ACTIVOS ──
    prisma.cliente.create({ data: {
      empresa: 'BLENDS INTELLIGENCE SAS',
      nit: '900.268.987-0',
      codigoCliente: '100026987',
      ciudad: 'Medellín',
      segmento: 'Bebidas',
      marcaProducto: 'JUNIPER - BEBIDAS CON Y SIN LICOR',
      contacto: 'JUAN DAVID ZAPATA',
      cargo: 'Gerente',
      telefono: '3012302698',
      email: 'juniperwater@gmail.com',
      contactoCompras: 'CRISTIAN RIVERA',
      telefonoCompras: '323 3228314',
      emailCompras: 'logistica@juniper-drinks.com',
      contactoPagos: 'DORA RUBIO / IRIS LOPEZ',
      telefonoPagos: '316 5217291',
      emailPagos: 'dora.rubio@juniper-drinks.com',
      horarioEntregas: 'L-V 7am-5pm',
      cierreFacturacion: 29,
      citasEntrega: 'AVISAR CON 1 DIA ANTES DE LA ENTREGA',
      condicionPago: 'CUPO $50.000.000 - CREDITO 60 dias',
      estado: 'Activo',
      direccion: 'BODEGA SAN BARTOLOME 7 BODEGA 7',
      productosInteres: 'Caja de Cartón Corrugado Simple, Cartón Plegadizo',
      notas: 'Pedidos en proceso. Van a hacer cambios en refs existentes de impresion.',
      pendientes: 'Solicitar cot de referencias nuevas: 3501768 SUGG TRANSPARENTE, 3435169 CAJA GENERICA 720CK',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'FAHILOS - FABRICA DE HILOS Y PRODUCTOS',
      nit: '890.534.900-0',
      codigoCliente: '100005349',
      ciudad: 'La Estrella',
      segmento: 'Textil',
      marcaProducto: 'FAHILOS - Hilos y cintas',
      contacto: 'JORGE MUÑOZ',
      cargo: 'Compras',
      telefono: '3173736655',
      email: 'compras@fahilos.com',
      contactoPagos: 'DIANA GRAJALES / DINA REQUENA',
      telefonoPagos: '4482120 EXT 603-604',
      emailPagos: 'contabilidad1@fahilos.com',
      horarioEntregas: 'L-V 8AM-4PM / SAB 8-11AM',
      cierreFacturacion: 26,
      citasEntrega: 'ADJUNTAR OC A LA FACTURA',
      condicionPago: 'CUPO $30.000.000 - CREDITO 60 dias',
      direccion: 'Cl 79B S #54-80 El Palmar - La Estrella',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'REVISION DE PRECIOS',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'PRODUCTOS SEBA SEBA SAS',
      nit: '900.668.200-0',
      codigoCliente: '100006682',
      ciudad: 'Itagüí',
      segmento: 'Alimentos',
      marcaProducto: 'ALIMENTOS HORNEADOS',
      contacto: 'GILMA CECILIA VELASQUEZ',
      telefono: '3117488803',
      email: 'gilmav8@hotmail.com',
      direccion: 'Cl. 85 #50-50 Itagui',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'EDDING COLOMBIA SAS',
      nit: '900.681.300-0',
      codigoCliente: '100006813',
      ciudad: 'Sabaneta',
      segmento: 'Industrial',
      marcaProducto: 'MARCADORES Y PRODUCTOS MAPLE',
      contacto: 'JULIO CESAR GARCIA',
      cargo: 'Gerente',
      telefono: '3172224757',
      email: 'jgarcia@edding.com',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple, Empaques Especiales',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'DULCE MOLIENDA SAS',
      nit: '900.268.600-0',
      codigoCliente: '100026860',
      ciudad: 'Medellín',
      segmento: 'Alimentos',
      marcaProducto: 'PANELA',
      contacto: 'NORMAN BUSTAMANTE',
      telefono: '3117497320',
      email: 'normanbustamante@une.net.co',
      estado: 'Activo',
      notas: 'Recoge en bodega Medellin',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'GRUPO AFIN FARMACEUTICA SAS BIC',
      nit: '900.287.090-0',
      codigoCliente: '100028709',
      ciudad: 'Sabaneta',
      segmento: 'Farmacéutico',
      marcaProducto: 'LABORATORIO FARMACEUTICO',
      contacto: '',
      telefono: '604 4030388',
      estado: 'Activo',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INVERSIONES BEROCOS SAS - CARTOPLAS',
      nit: '900.273.600-0',
      codigoCliente: '100027360',
      ciudad: 'Medellín',
      segmento: 'Industrial',
      marcaProducto: 'ELEMENTOS DE OFICINA Y ESTUDIO',
      contacto: 'ALEJANDRO CORREA',
      telefono: '312 757 06 96',
      direccion: 'Calle 29B 56-04',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'ECOBRIQUETAS SAS',
      nit: '900.331.080-0',
      codigoCliente: '100033108',
      ciudad: 'Medellín',
      segmento: 'Industrial',
      marcaProducto: 'CHISPA ECOLOGICA',
      contacto: 'JHON JAIRO',
      telefono: '3135320471',
      email: 'ecobriquetascol@gmail.com',
      estado: 'Activo',
      notas: 'Recoge en bodega Medellin',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'FROLADO - JURADO ZAPATA VALENTINA',
      codigoCliente: '100028008',
      ciudad: 'Medellín',
      segmento: 'Alimentos',
      marcaProducto: 'HELADOS FROLADO',
      contacto: 'FELIPE RENDON',
      telefono: '3173879986',
      email: 'valenzap2@gmail.com',
      direccion: 'Barrio Antioquia',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INDUSTRIAS LEO S A',
      nit: '890.001.418-0',
      codigoCliente: '100001418',
      ciudad: 'Sabaneta',
      segmento: 'Industrial',
      marcaProducto: 'METALURGICA',
      contacto: '',
      direccion: 'CRA 43A #61SUR 152 INT 181 Sabaneta',
      estado: 'Activo',
      productosInteres: 'Embalaje Industrial',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'DINAMICA EMPAQUES E IMPRESOS SAS',
      nit: '900.224.080-0',
      codigoCliente: '100022408',
      ciudad: 'Medellín',
      segmento: 'Impresos',
      marcaProducto: 'IMPRESOS INDUSTRIALES',
      contacto: 'JORGE ANDRES JARAMILLO',
      cargo: 'Gerente',
      telefono: '3185893368',
      email: 'andresjaramillo@litografiadinamica.com',
      estado: 'Activo',
      productosInteres: 'Láminas de Cartón, Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'ARUM LATAM SAS',
      nit: '900.306.960-0',
      codigoCliente: '100030696',
      ciudad: 'Medellín',
      segmento: 'Cosméticos',
      marcaProducto: 'POLVOS DE COLAGENO',
      contacto: 'LAURA GARCIA',
      cargo: 'Jefe administrativa y de operaciones',
      telefono: '3016214412',
      email: 'gerenciaarumlatam@gmail.com',
      direccion: 'Belen',
      estado: 'Activo',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'WELHOME SAS',
      nit: '900.351.180-0',
      codigoCliente: '100035118',
      ciudad: 'Itagüí',
      segmento: 'Industrial',
      marcaProducto: 'ESPONJAS LIMPIEZA',
      contacto: 'LINA VELEZ',
      telefono: '3014316080',
      email: 'lina.velez@welhome.com.co',
      web: 'welhome.com.co',
      direccion: 'CR 43 50 47 Itagui',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'ENDULZA TU VIDA SAS',
      nit: '900.266.920-0',
      codigoCliente: '100026692',
      ciudad: 'Girardota',
      segmento: 'Alimentos',
      marcaProducto: 'POSTRES',
      contacto: 'SARA CORREA',
      cargo: 'Gerente',
      email: 'saracorrea@endulzatuvida.com.co',
      direccion: 'Carrera 14 No. 1-11 Girardota',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple, Cartón Plegadizo',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'PRODUCTOS ALIMENTICIOS KONFYT SAS',
      nit: '890.003.220-0',
      codigoCliente: '100003220',
      ciudad: 'Medellín',
      segmento: 'Alimentos',
      marcaProducto: 'PRODUCTOS SIN AZUCAR',
      contacto: 'ANDREA ALVAREZ',
      cargo: 'Directora de Compras',
      telefono: '300 612 3856',
      email: 'andrea.alvarez@konfyt.com',
      direccion: 'Cra. 52b #8 Sur 31 Guayabal',
      estado: 'Activo',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales',
      pendientes: 'REVISION DE PRECIOS DE REF CLAVES PARA D1',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'ALIMENTOS ESTILO GOURMET SAS',
      nit: '900.096.140-0',
      codigoCliente: '100009614',
      ciudad: 'Itagüí',
      segmento: 'Alimentos',
      marcaProducto: 'CONSERVAS',
      contacto: '',
      web: 'estilogourmet.com.co',
      direccion: 'Cra. 42 No. 50A-28, Itagui',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'JP TIENE PENDIENTE REVISION DE PRECIOS DE REF CLAVES DEL CLIENTE PARA D1',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'NEROLI SAS',
      nit: '900.183.950-0',
      codigoCliente: '100018395',
      ciudad: 'Sabaneta',
      segmento: 'Cosméticos',
      marcaProducto: 'FRAGANCIAS - SHAMPOO - CREMAS Y AROMAS',
      contacto: '',
      direccion: 'Calle 80 Sur No 47F-07, Sabaneta',
      estado: 'Activo',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'GRUPO MAYA VELASQUEZ SAS',
      nit: '900.184.150-0',
      codigoCliente: '100018415',
      ciudad: 'Medellín',
      segmento: 'Textil',
      marcaProducto: 'GANCHOS ROPA',
      contacto: 'ALEJANDRO MAYA VELASQUEZ',
      telefono: '3176491477',
      email: 'gerencia@mayavelasquez.com.co',
      web: 'mayavelasquez.com.co',
      direccion: 'Zona Industrial Belen',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple, Embalaje Industrial',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'PREBEL SA BIC',
      nit: '890.005.313-0',
      codigoCliente: '100005313',
      ciudad: 'Medellín',
      segmento: 'Cosméticos',
      marcaProducto: 'COSMETICOS Y CUIDADO PERSONAL',
      contacto: 'YULIANA ANDREA CASTRO PEREZ',
      cargo: 'Jefe de negociaciones',
      telefono: '313 740 01 73',
      email: 'yuliana.castro@prebel.com.co',
      estado: 'Activo',
      notas: 'Oficinas en Guayabal - entregas en Rionegro',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales, Displays Comerciales',
      volumenMensual: 25000000,
    }}),

    prisma.cliente.create({ data: {
      empresa: 'GRUPO MAGIA NATURAL SAS',
      nit: '900.358.720-0',
      codigoCliente: '100035872',
      ciudad: 'Sabaneta',
      segmento: 'Cosméticos',
      marcaProducto: 'SHAMPOO Y TRATAMIENTOS CABELLO',
      contacto: 'JUAN DIEGO SANCHEZ',
      cargo: 'Dueño',
      telefono: '301 338 24 22',
      email: 'jsanchez465@hotmail.com',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'COT DE CAJA CORRIENTE CON CAMBIO DE COLOR A 1 TINTA Y CAMBIO CLISE',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INGEPRODUCTOS SAS',
      nit: '900.222.590-0',
      codigoCliente: '100022259',
      ciudad: 'Guarne',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS PARA HOGAR',
      contacto: 'RAUL HOLGUIN',
      cargo: 'Dueño',
      telefono: '317 645 50 27',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'REVISION DE PRECIOS Y LIMPIAR LA COT DE REFS INACTIVAS',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'LABORATORIOS M&J SAS',
      nit: '900.265.190-0',
      codigoCliente: '100026519',
      ciudad: 'Medellín',
      segmento: 'Farmacéutico',
      marcaProducto: 'JABONES',
      contacto: 'MARIA EUGENIA ARAY',
      cargo: 'Gerente General',
      telefono: '285 40 10',
      celular: '320 566 29 95',
      email: 'laboratoriosmjsas@gmail.com',
      direccion: 'Guayabal',
      estado: 'Activo',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'MARQUILLAS Y ACCESORIOS SA',
      nit: '890.000.694-0',
      codigoCliente: '100000694',
      ciudad: 'Sabaneta',
      segmento: 'Textil',
      marcaProducto: 'ETIQUETAS',
      contacto: 'JUAN RESTREPO',
      telefono: '320 663 57 06',
      celular: '311 747 91 76',
      email: 'juanrestrepo@marquiacces.com.co',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple, Embalaje Industrial',
      volumenMensual: 8000000,
    }}),

    prisma.cliente.create({ data: {
      empresa: 'PACHA MAMA GOURMET',
      nit: '900.349.770-0',
      codigoCliente: '100034977',
      ciudad: 'Medellín',
      segmento: 'Alimentos',
      marcaProducto: 'CONSERVAS',
      contacto: 'JORGE RESTREPO',
      telefono: '301 2425352',
      email: 'info@pachamamagourmet.com',
      direccion: 'Laureles',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple, Cartón Plegadizo',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'TERCOL SAS',
      nit: '900.367.810-0',
      codigoCliente: '100036781',
      ciudad: 'Medellín',
      segmento: 'Industrial',
      marcaProducto: 'TABLEROS ELECTRICOS - CONSTRUCCION',
      contacto: '',
      direccion: 'Zona Industrial de Belen',
      estado: 'Activo',
      productosInteres: 'Embalaje Industrial, Caja de Cartón Corrugado Doble',
      pendientes: 'PENDIENTE COT CON LOS CAMBIOS ACTUALIZADA',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INDUSTRIAS PLASTICAS ATH SAS',
      nit: '900.229.640-0',
      codigoCliente: '100022964',
      ciudad: 'Caldas',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS FRASCOS',
      contacto: 'LEIDY JOHANA JARAMILLO',
      cargo: 'Gerente',
      telefono: '31460 0908',
      email: 'gerencia@plasticasath.com',
      contactoCompras: 'NATALY BETANCOUR',
      cargo: 'Directora Calidad',
      telefonoCompras: '322 6820553',
      emailCompras: 'calidad@plasticasath.com',
      contactoPagos: 'LEIDY JOHANA JARAMILLO',
      horarioEntregas: 'L-V 7AM-4PM',
      cierreFacturacion: 29,
      condicionPago: 'CUPO $55.000.000 - CREDITO 30 dias',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'AUMENTO CUPO Y CREDITO Y PRECIOS PARA 2025 - MODIFICAR CLAVES DE ALGUNAS REFERENCIAS',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INVERSIONES HUMO SAS',
      nit: '900.359.840-0',
      codigoCliente: '100035984',
      ciudad: 'Medellín',
      segmento: 'Industrial',
      marcaProducto: 'AHUMADORES CARNE',
      contacto: 'ANDRES GONZALEZ',
      telefono: '350 503 84 61',
      celular: '318 301 44 02',
      email: 'gerencia@humobarriles.com',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    // ── EN COTIZACION ──
    prisma.cliente.create({ data: {
      empresa: 'PLASTICOS TRUHER',
      nit: '890.907.406-1',
      codigoCliente: '100003159',
      ciudad: 'Sabaneta',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: 'DANIEL TRUJILLO',
      cargo: 'Director de Negociacion',
      telefono: '604 305 11 00 Ext 257',
      email: 'dtrujillo@plasticostruher.com',
      contactoCompras: 'VERONICA PIEDRAHITA / DIANA CARCAMO',
      telefonoCompras: '310 4737795',
      emailCompras: 'vpiedrahita@plasticostruher.com',
      web: 'plasticostruher.com',
      direccion: 'Calle 67 Sur #48B-95, Sabaneta',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'JP TE COPIE EN CORREO A LOS CLIENTES - A LA ESPERA DE RESPUESTA. MUESTRAS EN CAMINO.',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'AVICOLA NACIONAL - AVINAL',
      nit: '890.005.245-0',
      codigoCliente: '100005245',
      ciudad: 'Medellín',
      segmento: 'Alimentos',
      marcaProducto: 'HUEVOS AVINAL',
      contacto: 'RAFAEL AYALA',
      telefono: '310 2153252',
      email: 'rafael.ayala@avinal.com.co',
      contactoCompras: 'MANUEL JUNCO',
      telefonoCompras: '315 2514977',
      emailCompras: 'manuel.junco@avinal.com.co',
      direccion: 'CRA 48 #20-237 AV LOS INDUSTRIALES',
      estado: 'Cotización',
      productosInteres: 'Embalaje Industrial, Caja de Cartón Corrugado Doble',
      notas: 'Estan quietos - reactivar a regreso de vacaciones',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'SELECTA COMPAÑIA DE CEREALES S',
      nit: '900.152.100-0',
      codigoCliente: '100015210',
      ciudad: 'La Estrella',
      segmento: 'Alimentos',
      marcaProducto: 'CEREALES',
      contacto: 'ANDRES DUQUE',
      telefono: '317 4412685',
      contactoCompras: 'NATALY',
      telefonoCompras: '318 8158064',
      emailCompras: 'compras1@cerealesselecta.com',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      notas: 'Estan quietos - reactivar a regreso de vacaciones',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'EXTIBLU SAS',
      nit: '900.188.100-0',
      codigoCliente: '100018810',
      ciudad: 'Rionegro',
      segmento: 'Industrial',
      marcaProducto: 'IMPORTADORA GRANDES SUPERFICIES',
      contacto: '',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'PENDIENTE COT 2025 PARA ENVIAR AL CLIENTE',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INCODI SAS',
      nit: '890.904.980-2',
      codigoCliente: '100004868',
      ciudad: 'Guarne',
      segmento: 'Plásticos',
      marcaProducto: 'ENVASES PLASTICOS',
      contacto: '',
      web: 'incodi.com.co',
      direccion: 'Autopista Medellin-Bogota Km 1.2, Vereda San Jose, Guarne',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    // ── RETOMAR ──
    prisma.cliente.create({ data: {
      empresa: 'TP COLOMBIA SAS',
      nit: '900.338.020-0',
      codigoCliente: '100033802',
      ciudad: 'Girardota',
      segmento: 'Plásticos',
      marcaProducto: 'TAPAS PLASTICAS',
      contacto: '',
      telefono: '454 62 31',
      email: 'inventarios@tpcolombia.co',
      direccion: 'km 25 entrada a Girardota - Parque Industrial Del Norte Bodegas 131',
      estado: 'Retomar',
      productosInteres: 'Embalaje Industrial',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'EXITO INDUSTRIAS - DIDETEXCO',
      nit: '900.364.950-0',
      codigoCliente: '100036495',
      ciudad: 'Medellín',
      segmento: 'Textil',
      marcaProducto: 'DIDETEXCO - ROPA',
      contacto: 'YEISON',
      estado: 'Retomar',
      productosInteres: 'Embalaje Industrial, Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'ACCESORIOS AVE MARIA',
      nit: '900.387.780-0',
      codigoCliente: '100038778',
      ciudad: 'Medellín',
      segmento: 'Textil',
      marcaProducto: 'ACCESORIOS DE MUJER',
      contacto: '',
      estado: 'Retomar',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    // ── PROSPECTOS (fuente: PROSPECTOS NATY 2026) ──
    prisma.cliente.create({ data: {
      empresa: 'STAR PLASTIC SAS',
      nit: '901.607.755-7',
      ciudad: 'La Estrella',
      segmento: 'Plásticos',
      marcaProducto: 'PRODUCTOS PLASTICOS',
      contacto: '',
      telefono: '604 408 9690',
      direccion: 'Carrera 49A #98A Sur-228, Bodega 20A, La Estrella',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      notas: 'Cotizacion y muestra enviadas',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'DLUCHI - LUISA CHIMA',
      nit: '900.784.595-9',
      ciudad: 'Guarne',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: 'LUISA CHIMA',
      celular: '305 231 5234',
      web: 'dluchi.com',
      direccion: 'Km 35 Elite 2, Guarne, Antioquia',
      estado: 'Prospecto',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'PLASTICOS G1',
      nit: '900.432.459-5',
      ciudad: 'Sabaneta',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: '',
      telefono: '350 260 4731',
      web: 'plasticosg1.com',
      direccion: 'Carrera 43A #61 Sur-152, Bodega 157, Sabaneta',
      estado: 'Prospecto',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'PLASTICOS MEDELLIN',
      nit: '890.900.559-6',
      ciudad: 'Itagüí',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: '',
      telefono: '604 371 6299',
      web: 'plasticosmedellin.com',
      direccion: 'Calle 37B #42-354, Itagui',
      estado: 'Prospecto',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'GRUPO SUMMIT',
      nit: '900.589.032-9',
      ciudad: 'Itagüí',
      segmento: 'Industrial',
      marcaProducto: 'INDUSTRIAL',
      contacto: '',
      telefono: '604 607 4116',
      web: 'gruposummit.com.co',
      direccion: 'Carrera 42 #54A-155, Interior 1002, Itagui',
      estado: 'Prospecto',
      productosInteres: 'Embalaje Industrial',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INDUSTRIAS PEVENCOL',
      nit: '901.156.604-7',
      ciudad: 'Itagüí',
      segmento: 'Químicos',
      marcaProducto: 'PRODUCTOS QUIMICOS',
      contacto: '',
      telefono: '604 423 7826',
      web: 'pevencol.com',
      direccion: 'Carrera 47 #66-107, Itagui',
      estado: 'Prospecto',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'MICROPLAS - COLDEPLAST',
      nit: '890.905.790-4',
      ciudad: 'Itagüí',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: '',
      telefono: '604 372 0111',
      web: 'microplast.com.co',
      direccion: 'Cra. 42 #53-116, Itagui',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      notas: 'Correo enviado - pendiente respuesta',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'WEST QUIMICA',
      nit: '890.917.780-2',
      ciudad: 'La Estrella',
      segmento: 'Químicos',
      marcaProducto: 'QUIMICOS',
      contacto: '',
      telefono: '604 372 0303',
      web: 'westquimica.com',
      direccion: 'Carrera 50 #76D Sur-52, La Estrella',
      estado: 'Prospecto',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'UTOPICK - U TO PICK',
      nit: '901.123.220-0',
      ciudad: 'Medellín',
      segmento: 'Industrial',
      marcaProducto: 'LOGISTICA E-COMMERCE',
      contacto: '',
      telefono: '304 629 3712',
      celular: '310 374 7721',
      web: 'utopick.co',
      direccion: 'Carrera 57 #28-53, Medellin',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple, Embalaje Industrial',
      notas: 'Llamada realizada - en proceso',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'FRYSCOL.COM',
      nit: '901.448.512-1',
      ciudad: 'Medellín',
      segmento: 'Alimentos',
      marcaProducto: 'ALIMENTOS FRITOS',
      contacto: '',
      telefono: '300 709 1262',
      celular: '318 734 5501',
      web: 'fryscol.com',
      direccion: 'Cra 77A #49A-19, Medellin',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      notas: 'Correo enviado - pendiente respuesta',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'DMURANO',
      nit: '900.720.809-5',
      ciudad: 'Medellín',
      segmento: 'Industrial',
      marcaProducto: 'INDUSTRIAL',
      contacto: '',
      telefono: '604 444 1150',
      direccion: 'Calle 50 #23-47, Barrio San Juan, Medellin',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      notas: 'Visita realizada',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'INDUSTRIAS PLASTICAS DE MEDELLIN',
      nit: '900.259.734-5',
      ciudad: 'Medellín',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: '',
      telefono: '604 444 8369',
      direccion: 'Carrera 52 #6 Sur-90, Guayabal, Medellin',
      estado: 'Cotización',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      notas: 'Correo enviado - pendiente respuesta',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'FRUVESA FOODS',
      nit: '901.266.969-1',
      ciudad: 'La Estrella',
      segmento: 'Alimentos',
      marcaProducto: 'ALIMENTOS',
      contacto: '',
      telefono: '604 444 3999',
      celular: '317 827 7533',
      web: 'fruvesafoods.com',
      direccion: 'Carrera 54 #79AA Sur-150, La Estrella',
      estado: 'Prospecto',
      productosInteres: 'Caja de Cartón Corrugado Simple',
    }}),

    prisma.cliente.create({ data: {
      empresa: 'LABORATORIOS DENTAID',
      nit: '900.670.137-9',
      ciudad: 'Sabaneta',
      segmento: 'Farmacéutico',
      marcaProducto: 'PRODUCTOS DENTALES',
      contacto: '',
      telefono: '604 444 7548',
      web: 'dentaid.co',
      direccion: 'Carrera 49 #61 Sur-540 BG 144, Sabaneta',
      estado: 'Prospecto',
      productosInteres: 'Cartón Plegadizo, Empaques Especiales',
    }}),

    // Cliente Farmaplast (mencionado varias veces en DIARIO)
    prisma.cliente.create({ data: {
      empresa: 'FARMAPLAST',
      ciudad: 'Medellín',
      segmento: 'Farmacéutico',
      marcaProducto: 'PLASTICOS FARMACEUTICOS',
      contacto: '',
      estado: 'Activo',
      productosInteres: 'Cartón Plegadizo',
      notas: 'Cliente portal terceros activo - pedidos en curso',
    }}),

    // Plasticos Correa (activo reciente)
    prisma.cliente.create({ data: {
      empresa: 'PLASTICOS CORREA',
      nit: '900.380.740-0',
      codigoCliente: '100038074',
      ciudad: 'Girardota',
      segmento: 'Plásticos',
      marcaProducto: 'PLASTICOS',
      contacto: 'CINDY PENAGOS',
      cargo: 'Auxiliar compras',
      telefonoCompras: '300 3197631',
      emailCompras: 'auxcompras@plasticoscorrea.com',
      estado: 'Activo',
      productosInteres: 'Caja de Cartón Corrugado Simple',
      pendientes: 'ACTUALIZAR COT A PRECIOS 2025 - QUIERE EMPEZAR YA. MUESTRAS OK - CLIENTE MANDA ARTES PARA HACER FT',
    }}),
  ])

  console.log(`Creados ${clientes.length} clientes reales`)

  // ─── OPORTUNIDADES ───
  const oportunidades = await Promise.all([
    prisma.oportunidad.create({ data: {
      titulo: 'Caja corrugada Juniper - nueva impresion',
      valor: 18000000,
      etapa: 'Cotización',
      probabilidad: 60,
      fechaCierre: new Date('2026-04-15'),
      producto: 'Cartón Plegadizo',
      descripcion: 'Cambio de impresion en referencias existentes + referencias nuevas 720CK',
      clienteId: clientes[0].id, // Blends/Juniper
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Contrato caja corrugada Prebel',
      valor: 45000000,
      etapa: 'Negociación',
      probabilidad: 75,
      fechaCierre: new Date('2026-04-01'),
      producto: 'Cartón Plegadizo',
      descripcion: 'Contrato anual empaques cosméticos y cuidado personal',
      clienteId: clientes[18].id, // Prebel
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Cajas corrugadas Plasticos Truher',
      valor: 22000000,
      etapa: 'Cotización',
      probabilidad: 50,
      fechaCierre: new Date('2026-03-30'),
      producto: 'Caja de Cartón Corrugado Simple',
      descripcion: 'Cotización enviada - esperando respuesta del cliente',
      clienteId: clientes[27].id, // Plasticos Truher
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Embalaje ATH plasticos frascos',
      valor: 15000000,
      etapa: 'Negociación',
      probabilidad: 80,
      fechaCierre: new Date('2026-03-25'),
      producto: 'Caja de Cartón Corrugado Simple',
      descripcion: 'Aumento cupo y nuevos precios 2025 - modificar claves de referencias',
      clienteId: clientes[25].id, // ATH
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Empaques nuevos AVINAL huevos',
      valor: 28000000,
      etapa: 'Contacto Inicial',
      probabilidad: 20,
      fechaCierre: new Date('2026-05-01'),
      producto: 'Embalaje Industrial',
      descripcion: 'Reactivacion cliente - en proceso de creacion portal terceros',
      clienteId: clientes[28].id, // Avinal
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Cajas corrugadas Marquillas y Accesorios',
      valor: 8000000,
      etapa: 'Ganado',
      probabilidad: 100,
      fechaCierre: new Date('2026-02-28'),
      producto: 'Caja de Cartón Corrugado Simple',
      descripcion: 'Pedidos recurrentes, cliente activo y fiel',
      clienteId: clientes[22].id, // Marquillas
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Prospeccion Plasticos Correa',
      valor: 12000000,
      etapa: 'Cotización',
      probabilidad: 65,
      fechaCierre: new Date('2026-04-10'),
      producto: 'Caja de Cartón Corrugado Simple',
      descripcion: 'Muestras OK - cliente envia artes para finalizar FT. Quiere empezar ya.',
      clienteId: clientes[clientes.length - 1].id, // Plasticos Correa
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Primera cotizacion Star Plastic',
      valor: 9000000,
      etapa: 'Cotización',
      probabilidad: 45,
      fechaCierre: new Date('2026-04-20'),
      producto: 'Caja de Cartón Corrugado Simple',
      descripcion: 'Cotizacion y muestra enviadas - esperar respuesta',
      clienteId: clientes[35].id, // Star Plastic (index approx)
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Cajas Konfyt productos D1',
      valor: 16000000,
      etapa: 'Negociación',
      probabilidad: 70,
      fechaCierre: new Date('2026-03-28'),
      producto: 'Cartón Plegadizo',
      descripcion: 'Revision de precios de referencias claves del cliente para D1',
      clienteId: clientes[14].id, // Konfyt
    }}),
    prisma.oportunidad.create({ data: {
      titulo: 'Empaques UTOPICK e-commerce',
      valor: 20000000,
      etapa: 'Cotización',
      probabilidad: 55,
      fechaCierre: new Date('2026-04-30'),
      producto: 'Caja de Cartón Corrugado Simple',
      descripcion: 'Empresa de logistica e-commerce - alto potencial de volumen',
      clienteId: clientes[43].id, // Utopick (approx)
    }}),
  ])

  console.log(`Creadas ${oportunidades.length} oportunidades`)

  // ─── ACTIVIDADES recientes ───
  const now = new Date()
  const d = (days) => new Date(now.getTime() + days * 86400000)

  const actividades = await Promise.all([
    prisma.actividad.create({ data: {
      tipo: 'Cotización Enviada',
      fecha: d(-2),
      descripcion: 'Cotizacion y muestras enviadas a Star Plastic SAS. Referencias de caja corrugada 720CK.',
      resultado: 'Neutral',
      proximaAccion: 'Llamar para confirmar recepcion de muestras y resolver dudas',
      fechaProxima: d(2),
      clienteId: clientes[35].id,
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Email',
      fecha: d(-3),
      descripcion: 'Correo enviado a Microplas-Coldeplast con propuesta de caja corrugada. Pendiente respuesta.',
      resultado: 'Neutral',
      proximaAccion: 'Seguimiento por telefono si no hay respuesta en 3 dias',
      fechaProxima: d(1),
      clienteId: clientes[41].id, // Microplas approx
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Llamada',
      fecha: d(-1),
      descripcion: 'Llamada a UTOPICK. Confirmaron interes en cajas para despacho de pedidos online. Solicitan cotizacion formal.',
      resultado: 'Positivo',
      proximaAccion: 'Enviar cotizacion con precios por volumen',
      fechaProxima: d(2),
      clienteId: clientes[43].id,
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Visita',
      fecha: d(-4),
      descripcion: 'Visita a DMURANO. Se presento portafolio de cajas corrugadas. Buen recibimiento, piden cotizacion.',
      resultado: 'Positivo',
      proximaAccion: 'Enviar cotizacion segun medidas acordadas en visita',
      fechaProxima: d(3),
      clienteId: clientes[45].id, // Dmurano approx
    }}),
    prisma.actividad.create({ data: {
      tipo: 'WhatsApp',
      fecha: d(-1),
      descripcion: 'Confirmacion con Plasticos Correa: muestras recibidas y aprobadas. Esperando envio de artes por parte del cliente.',
      resultado: 'Positivo',
      proximaAccion: 'Recordar al cliente que envie los artes para generar FT',
      fechaProxima: d(5),
      clienteId: clientes[clientes.length - 1].id,
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Reunión',
      fecha: d(-5),
      descripcion: 'Reunion de negociacion con Prebel. Acordamos precios anuales y volumenes. En proceso firma de contrato.',
      resultado: 'Positivo',
      proximaAccion: 'Enviar contrato formal para revision y firma',
      fechaProxima: d(3),
      clienteId: clientes[18].id,
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Email',
      fecha: d(-6),
      descripcion: 'Correo de seguimiento a Plasticos Truher - cotizacion ya enviada. No hay respuesta aun.',
      resultado: 'Sin Respuesta',
      proximaAccion: 'Llamar directamente a Veronica Piedrahita en compras',
      fechaProxima: d(1),
      clienteId: clientes[27].id,
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Llamada',
      fecha: d(-7),
      descripcion: 'Llamada a Grupo Afin Farmaceutica. Confirman necesidad de cajas para nuevo producto. Solicitan visita tecnica.',
      resultado: 'Positivo',
      proximaAccion: 'Agendar visita tecnica a la planta en Sabaneta',
      fechaProxima: d(4),
      clienteId: clientes[5].id,
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Cotización Enviada',
      fecha: d(-3),
      descripcion: 'Cotizacion enviada a FRYSCOL.COM para cajas corrugadas linea alimentos fritos. Precios por volumen incluidos.',
      resultado: 'Neutral',
      proximaAccion: 'Seguimiento por WhatsApp en 4 dias',
      fechaProxima: d(4),
      clienteId: clientes[44].id, // Fryscol approx
    }}),
    prisma.actividad.create({ data: {
      tipo: 'Llamada',
      fecha: d(-10),
      descripcion: 'Reactivacion de Industrias Plasticas de Medellin. Correo enviado. Sin respuesta hasta ahora.',
      resultado: 'Neutral',
      proximaAccion: 'Visita presencial al taller para mostrar muestras fisicas',
      fechaProxima: d(7),
      clienteId: clientes[46].id, // IPM approx
    }}),
  ])

  console.log(`Creadas ${actividades.length} actividades`)

  // ─── TAREAS ───
  const tareas = await Promise.all([
    prisma.tarea.create({ data: {
      titulo: 'Llamar a Plasticos Truher - seguimiento cotizacion',
      descripcion: 'Contactar a Veronica Piedrahita en compras. Cotizacion enviada hace mas de una semana sin respuesta.',
      fechaLimite: d(1),
      prioridad: 'Alta',
      tipo: 'Llamada',
      clienteId: clientes[27].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Enviar contrato a Prebel para firma',
      descripcion: 'Contrato anual negociado. Revision de clausulas de precios y volumenes acordados.',
      fechaLimite: d(2),
      prioridad: 'Alta',
      tipo: 'Email',
      clienteId: clientes[18].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Cotizacion formal para UTOPICK',
      descripcion: 'Cajas corrugadas para e-commerce. Incluir precios escalonados por volumen.',
      fechaLimite: d(2),
      prioridad: 'Alta',
      tipo: 'Seguimiento',
      clienteId: clientes[43].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Recordar a Plasticos Correa enviar artes',
      descripcion: 'Muestras aprobadas. Falta que el cliente envie los artes para generar ficha tecnica.',
      fechaLimite: d(3),
      prioridad: 'Alta',
      tipo: 'WhatsApp',
      clienteId: clientes[clientes.length - 1].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Seguimiento Star Plastic - confirmar muestras',
      descripcion: 'Llamar para confirmar recepcion de muestras 720CK. Resolver dudas tecnicas.',
      fechaLimite: d(3),
      prioridad: 'Alta',
      tipo: 'Llamada',
      clienteId: clientes[35].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Agendar visita tecnica a Grupo Afin Farmaceutica',
      descripcion: 'Solicitan visita para definir specs de caja para nuevo producto. Confirmar fecha.',
      fechaLimite: d(4),
      prioridad: 'Media',
      tipo: 'Visita',
      clienteId: clientes[5].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Actualizar cotizacion ATH Plasticos - precios 2025',
      descripcion: 'Actualizar precios 2025 y verificar claves de referencias con cambios solicitados.',
      fechaLimite: d(4),
      prioridad: 'Media',
      tipo: 'Seguimiento',
      clienteId: clientes[25].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'WhatsApp seguimiento a FRYSCOL',
      descripcion: 'Cotizacion enviada hace 3 dias. Hacer seguimiento amable por WhatsApp.',
      fechaLimite: d(5),
      prioridad: 'Media',
      tipo: 'WhatsApp',
      clienteId: clientes[44].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Reactivar clientes Cotizacion: AVINAL y Selecta Cereales',
      descripcion: 'Estan quietos desde antes de vacaciones. Enviar mensaje de reactivacion amigable.',
      fechaLimite: d(7),
      prioridad: 'Media',
      tipo: 'Email',
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Visita a Industrias Plasticas de Medellin',
      descripcion: 'Correo enviado sin respuesta. Visita presencial para mostrar muestras fisicas.',
      fechaLimite: d(10),
      prioridad: 'Baja',
      tipo: 'Visita',
      clienteId: clientes[46].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Revision de precios Konfyt para D1',
      descripcion: 'JP tiene pendiente revision de precios de referencias claves del cliente para canal D1.',
      fechaLimite: d(7),
      prioridad: 'Alta',
      tipo: 'Seguimiento',
      clienteId: clientes[14].id,
    }}),
    prisma.tarea.create({ data: {
      titulo: 'Prospectar: Laboratorios Dentaid y Fruvesa Foods',
      descripcion: 'Dos prospectos identificados en zona La Estrella / Sabaneta. Primer contacto por telefono.',
      fechaLimite: d(14),
      prioridad: 'Baja',
      tipo: 'Llamada',
    }}),
  ])

  console.log(`Creadas ${tareas.length} tareas`)
  console.log('Datos reales de Cartones America cargados exitosamente!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
